# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-02 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='holder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='held_jobs', to='users.User'),
        ),
    ]
