# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-02 20:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190202_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='created_jobs', to='users.User'),
        ),
    ]
